/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectgroup;

import java.io.File;
import java.util.Date;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import static java.nio.file.Files.write;
import static java.nio.file.Files.write;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KWANNATTHA
 */
public class MenuFrame extends javax.swing.JFrame {
        public MenuFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JLabel();
        Esspresso = new javax.swing.JLabel();
        Americano = new javax.swing.JLabel();
        Latte = new javax.swing.JLabel();
        Cappuccino = new javax.swing.JLabel();
        GreenTea = new javax.swing.JLabel();
        ThaiTea = new javax.swing.JLabel();
        CoCoa = new javax.swing.JLabel();
        Hot1 = new javax.swing.JLabel();
        Ice1 = new javax.swing.JLabel();
        Frappe1 = new javax.swing.JLabel();
        Hot2 = new javax.swing.JLabel();
        Ice2 = new javax.swing.JLabel();
        Frappe2 = new javax.swing.JLabel();
        Milk = new javax.swing.JLabel();
        MilkTea = new javax.swing.JLabel();
        LemonTea = new javax.swing.JLabel();
        Milo = new javax.swing.JLabel();
        Nescafe = new javax.swing.JLabel();
        NescafeTea = new javax.swing.JLabel();
        ItalianSoda = new javax.swing.JLabel();
        RedlimeSoda = new javax.swing.JLabel();
        HoneylimeSoda = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        Baht = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Order = new javax.swing.JTextPane();
        EsspressoH = new javax.swing.JCheckBox();
        AmericanoH = new javax.swing.JCheckBox();
        LatteH = new javax.swing.JCheckBox();
        CappuccinoH = new javax.swing.JCheckBox();
        GreenTeaH = new javax.swing.JCheckBox();
        ThaiTeaH = new javax.swing.JCheckBox();
        CoCoaH = new javax.swing.JCheckBox();
        EsspressoI = new javax.swing.JCheckBox();
        EsspressoF = new javax.swing.JCheckBox();
        AmericanoI = new javax.swing.JCheckBox();
        LatteI = new javax.swing.JCheckBox();
        LatteF = new javax.swing.JCheckBox();
        CappuccinoI = new javax.swing.JCheckBox();
        CappuccinoF = new javax.swing.JCheckBox();
        GreenTeaI = new javax.swing.JCheckBox();
        GreenTeaF = new javax.swing.JCheckBox();
        ThaiTeaI = new javax.swing.JCheckBox();
        ThaiTeaF = new javax.swing.JCheckBox();
        CoCoaI = new javax.swing.JCheckBox();
        CoCoaF = new javax.swing.JCheckBox();
        MilkH = new javax.swing.JCheckBox();
        MiloH = new javax.swing.JCheckBox();
        NescafeH = new javax.swing.JCheckBox();
        NescafeTeaH = new javax.swing.JCheckBox();
        MiloI = new javax.swing.JCheckBox();
        NescafeI = new javax.swing.JCheckBox();
        NescafeTeaI = new javax.swing.JCheckBox();
        RedLimeSodaI = new javax.swing.JCheckBox();
        HoneyLimeSodaI = new javax.swing.JCheckBox();
        MilkI = new javax.swing.JCheckBox();
        MilkTeaI = new javax.swing.JCheckBox();
        LemonTeaI = new javax.swing.JCheckBox();
        MiloF = new javax.swing.JCheckBox();
        NescafeF = new javax.swing.JCheckBox();
        NescafeTeaF = new javax.swing.JCheckBox();
        ItalianSodaF = new javax.swing.JCheckBox();
        MilkF = new javax.swing.JCheckBox();
        MilkTeaF = new javax.swing.JCheckBox();
        LemonTeaF = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(51, 153, 255));
        Menu.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        Menu.setForeground(new java.awt.Color(102, 204, 255));
        Menu.setText("Coffee Background Menu");

        Esspresso.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Esspresso.setForeground(new java.awt.Color(51, 51, 51));
        Esspresso.setText("Esspresso");

        Americano.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Americano.setForeground(new java.awt.Color(51, 51, 51));
        Americano.setText("Americano");

        Latte.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Latte.setForeground(new java.awt.Color(51, 51, 51));
        Latte.setText("Latte");

        Cappuccino.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Cappuccino.setForeground(new java.awt.Color(51, 51, 51));
        Cappuccino.setText("Cappuccino");

        GreenTea.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        GreenTea.setForeground(new java.awt.Color(51, 51, 51));
        GreenTea.setText("Green Tea");

        ThaiTea.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ThaiTea.setForeground(new java.awt.Color(51, 51, 51));
        ThaiTea.setText("Thai Tea");

        CoCoa.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CoCoa.setForeground(new java.awt.Color(51, 51, 51));
        CoCoa.setText("CoCoa");

        Hot1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Hot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hot1.setText("Hot");

        Ice1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Ice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ice1.setText("Ice");

        Frappe1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Frappe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frappe1.setText("Frappe");

        Hot2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Hot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hot2.setText("Hot");

        Ice2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Ice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ice2.setText("Ice");

        Frappe2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Frappe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frappe2.setText("Frappe");

        Milk.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Milk.setText("Milk");

        MilkTea.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkTea.setText("MilkTea");

        LemonTea.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LemonTea.setText("Lemon Tea");

        Milo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Milo.setText("Milo");

        Nescafe.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Nescafe.setText("Nescafe");

        NescafeTea.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeTea.setText("NescafeTea");

        ItalianSoda.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ItalianSoda.setText("Italian Soda");

        RedlimeSoda.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        RedlimeSoda.setText("Red Lime Soda");

        HoneylimeSoda.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        HoneylimeSoda.setText("Honey Lime Soda");

        Price.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Price.setText("Price");

        btnPayment.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        Baht.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jScrollPane1.setViewportView(Order);

        EsspressoH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        EsspressoH.setText("35");
        EsspressoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsspressoHActionPerformed(evt);
            }
        });

        AmericanoH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        AmericanoH.setText("35");

        LatteH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LatteH.setText("35");

        CappuccinoH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CappuccinoH.setText("35");

        GreenTeaH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        GreenTeaH.setText("20");

        ThaiTeaH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ThaiTeaH.setText("20");

        CoCoaH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CoCoaH.setText("20");

        EsspressoI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        EsspressoI.setText("40");
        EsspressoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsspressoIActionPerformed(evt);
            }
        });

        EsspressoF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        EsspressoF.setText("50");
        EsspressoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsspressoFActionPerformed(evt);
            }
        });

        AmericanoI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        AmericanoI.setText("40");

        LatteI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LatteI.setText("40");

        LatteF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LatteF.setText("50");

        CappuccinoI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CappuccinoI.setText("40");

        CappuccinoF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CappuccinoF.setText("50");

        GreenTeaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        GreenTeaI.setText("25");

        GreenTeaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        GreenTeaF.setText("30");

        ThaiTeaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ThaiTeaI.setText("25");

        ThaiTeaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ThaiTeaF.setText("30");

        CoCoaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CoCoaI.setText("25");

        CoCoaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CoCoaF.setText("30");

        MilkH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkH.setText("20");
        MilkH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkHActionPerformed(evt);
            }
        });

        MiloH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MiloH.setText("20");

        NescafeH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeH.setText("20");
        NescafeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NescafeHActionPerformed(evt);
            }
        });

        NescafeTeaH.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeTeaH.setText("20");

        MiloI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MiloI.setText("25");
        MiloI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiloIActionPerformed(evt);
            }
        });

        NescafeI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeI.setText("25");

        NescafeTeaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeTeaI.setText("25");

        RedLimeSodaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        RedLimeSodaI.setText("25");

        HoneyLimeSodaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        HoneyLimeSodaI.setText("25");

        MilkI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkI.setText("25");
        MilkI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkIActionPerformed(evt);
            }
        });

        MilkTeaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkTeaI.setText("25");

        LemonTeaI.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LemonTeaI.setText("25");

        MiloF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MiloF.setText("30");

        NescafeF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeF.setText("30");

        NescafeTeaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NescafeTeaF.setText("30");

        ItalianSodaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ItalianSodaF.setText("25");

        MilkF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkF.setText("30");
        MilkF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkFActionPerformed(evt);
            }
        });

        MilkTeaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        MilkTeaF.setText("30");

        LemonTeaF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LemonTeaF.setText("30");

        btnAdd.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Baht, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Esspresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Latte, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GreenTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Americano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThaiTea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoCoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LatteH)
                                                        .addComponent(CappuccinoH))
                                                    .addGap(23, 23, 23))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(AmericanoH)
                                                            .addGap(0, 29, Short.MAX_VALUE))
                                                        .addComponent(EsspressoH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(GreenTeaH)
                                                .addGap(23, 23, 23)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ThaiTeaH)
                                            .addGap(23, 23, 23)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CoCoaH)
                                        .addGap(23, 23, 23))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hot1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EsspressoI, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Ice1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Frappe1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EsspressoF, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LatteF)
                                                    .addComponent(CappuccinoF)
                                                    .addComponent(ThaiTeaF)
                                                    .addComponent(GreenTeaF)
                                                    .addComponent(CoCoaF))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CoCoaI)
                                    .addComponent(ThaiTeaI)
                                    .addComponent(GreenTeaI)
                                    .addComponent(LatteI)
                                    .addComponent(AmericanoI)
                                    .addComponent(CappuccinoI))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Milk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MilkTea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LemonTea)
                                        .addComponent(Milo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nescafe, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NescafeTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ItalianSoda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RedlimeSoda))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hot2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MiloH)
                                    .addComponent(NescafeTeaH)
                                    .addComponent(MilkH)
                                    .addComponent(NescafeH)))
                            .addComponent(HoneylimeSoda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ice2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LemonTeaI)
                                    .addComponent(MiloI)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(MilkI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MilkTeaI, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LemonTeaF)
                                            .addComponent(MiloF)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(MilkF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MilkTeaF, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(Frappe2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NescafeTeaI)
                                            .addComponent(RedLimeSodaI)
                                            .addComponent(HoneyLimeSodaI))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NescafeTeaF)
                                            .addComponent(ItalianSodaF)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NescafeI)
                                        .addGap(28, 28, 28)
                                        .addComponent(NescafeF)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Price, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(Baht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ice1)
                            .addComponent(Hot1)
                            .addComponent(Frappe1))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Esspresso)
                            .addComponent(EsspressoI)
                            .addComponent(EsspressoF)
                            .addComponent(EsspressoH))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Americano)
                            .addComponent(AmericanoH)
                            .addComponent(AmericanoI))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Latte)
                            .addComponent(LatteH)
                            .addComponent(LatteI)
                            .addComponent(LatteF)
                            .addComponent(LemonTea))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cappuccino)
                            .addComponent(CappuccinoH)
                            .addComponent(CappuccinoI)
                            .addComponent(CappuccinoF))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GreenTeaH)
                            .addComponent(GreenTeaI)
                            .addComponent(GreenTeaF))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThaiTea)
                            .addComponent(ThaiTeaH)
                            .addComponent(ThaiTeaI)
                            .addComponent(ThaiTeaF))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoCoa)
                            .addComponent(CoCoaH)
                            .addComponent(CoCoaI)
                            .addComponent(CoCoaF))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayment)
                    .addComponent(btnClear)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hot2)
                            .addComponent(Frappe2)
                            .addComponent(Ice2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MilkH)
                                    .addComponent(Milk))
                                .addGap(18, 18, 18)
                                .addComponent(MilkTea)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MiloH)
                                    .addComponent(MiloI)
                                    .addComponent(MiloF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MilkI)
                                .addGap(18, 18, 18)
                                .addComponent(MilkTeaI)
                                .addGap(24, 24, 24)
                                .addComponent(LemonTeaI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MilkF)
                                .addGap(18, 18, 18)
                                .addComponent(MilkTeaF)
                                .addGap(24, 24, 24)
                                .addComponent(LemonTeaF)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NescafeI)
                                .addComponent(NescafeH))
                            .addComponent(NescafeF))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NescafeTeaH)
                            .addComponent(NescafeTea))
                        .addGap(26, 26, 26)
                        .addComponent(ItalianSoda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NescafeTeaI)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NescafeTeaF)
                                        .addGap(22, 22, 22)
                                        .addComponent(ItalianSodaF)))
                                .addGap(18, 18, 18)
                                .addComponent(RedLimeSodaI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Milo)
                                .addGap(18, 18, 18)
                                .addComponent(Nescafe)
                                .addGap(139, 139, 139)
                                .addComponent(RedlimeSoda)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoneyLimeSodaI)
                            .addComponent(HoneylimeSoda))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        Order.setText("");
        Baht.setText("");
        EsspressoH.setSelected(false);
        EsspressoI.setSelected(false);
        EsspressoF.setSelected(false);
        AmericanoH.setSelected(false);
        AmericanoI.setSelected(false);   
        LatteH.setSelected(false);
        LatteI.setSelected(false);
        LatteF.setSelected(false);
        CappuccinoH.setSelected(false);
        CappuccinoI.setSelected(false);
        CappuccinoF.setSelected(false);
        GreenTeaH.setSelected(false);
        GreenTeaI.setSelected(false);
        GreenTeaF.setSelected(false);
        ThaiTeaH.setSelected(false);
        ThaiTeaI.setSelected(false);
        ThaiTeaF.setSelected(false);
        CoCoaH.setSelected(false);
        CoCoaI.setSelected(false);
        CoCoaF.setSelected(false);
        MilkH.setSelected(false);
        MilkI.setSelected(false);
        MilkF.setSelected(false);
        MilkTeaI.setSelected(false);
        MilkTeaF.setSelected(false);
        LemonTeaI.setSelected(false);
        LemonTeaF.setSelected(false);
        MiloH.setSelected(false);
        MiloI.setSelected(false);
        MiloF.setSelected(false);
        NescafeH.setSelected(false);
        NescafeI.setSelected(false);
        NescafeF.setSelected(false);
        NescafeTeaH.setSelected(false);
        NescafeTeaI.setSelected(false);
        NescafeTeaF.setSelected(false);
        ItalianSodaF.setSelected(false);
        RedLimeSodaI.setSelected(false);
        HoneyLimeSodaI.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void EsspressoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsspressoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsspressoHActionPerformed

    private void EsspressoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsspressoIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsspressoIActionPerformed

    private void EsspressoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsspressoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsspressoFActionPerformed

    private void MilkHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MilkHActionPerformed

    private void MilkIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MilkIActionPerformed

    private void MilkFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MilkFActionPerformed

    private void MiloIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiloIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiloIActionPerformed

    private void NescafeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NescafeHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NescafeHActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        String text = "";
        int price = 0;
        if(EsspressoH.isSelected() == true)
        {
            price = price + 35;
            text += ("Esspresso Hot   " + 35 + "  Baht\n");
        }
        if(EsspressoI.isSelected() == true)
        {
            price = price + 40;
            text += ("Esspresso Ice  " + 40 + "  Baht\n");
        }
        if(EsspressoF.isSelected() == true)
        {
            price = price + 50;
            text += ("Esspresso Frappe  " + 50 + "  Baht\n");
        }
        if(AmericanoH.isSelected() == true)
        {
            price = price + 35;
            text += ("Americano Hot  " + 35 + "  Baht\n");
        }
        if(AmericanoI.isSelected() == true)
        {
            price = price + 40;
            text += ("Americano Ice  " + 40 + "  Baht\n");
        }
        if(LatteH.isSelected() == true)
        {
            price = price + 35;
            text += ("Latte Hot  " + 35 + "  Baht\n");
        }
        if(LatteI.isSelected() == true)
        {
            price = price + 40;
            text += ("Latte Ice  " + 40 + "  Baht\n");
        }
        if(LatteF.isSelected() == true)
        {
            price = price + 50;
            text += ("Latte Frappe  " + 50 + "  Baht\n");
        }
        if(CappuccinoH.isSelected() == true)
        {
            price = price + 35;
            text += ("Cappuccino Hot  " + 35 + "  Baht\n");
        }
        if(CappuccinoI.isSelected() == true)
        {
            price = price + 40;
            text += ("Cappuccino Ice  " + 40 + "  Baht\n");
        }
        if(CappuccinoF.isSelected() == true)
        {
            price = price + 50;
            text += ("Cappuccino Frappe  " + 50 + "  Baht\n");
        }
        if(GreenTeaH.isSelected() == true)
        {
            price = price + 20;
            text += ("Green Tea Hot  " + 20 + "  Baht\n");
        }
        if(GreenTeaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Green Tea Ice  " + 25 + "  Baht\n");
        }
        if(GreenTeaF.isSelected() == true)
        {
            price = price + 30;
            text += ("Green Tea Frappe  " + 30 + "  Baht\n");
        }
        if(ThaiTeaH.isSelected() == true)
        {
            price = price + 20;
            text += ("Thai Tea Hot  " + 20 + "  Baht\n");
        }
        if(ThaiTeaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Thai Tea Ice  " + 25 + "  Baht\n");
        }
        if(ThaiTeaF.isSelected() == true)
        {
            price = price + 30;
            text += ("Thai Tea Frappe  " + 30 + "  Baht\n");
        }
        if(CoCoaH.isSelected() == true)
        {
            price = price + 20;
            text += ("CoCoaH Hot  " + 20 + "  Baht\n");
        }
        if(CoCoaI.isSelected() == true)
        {
            price = price + 25;
            text += ("CoCoaH Ice  " + 25 + " Baht\n");
        }
        if(CoCoaF.isSelected() == true)
        {
            price = price + 30;
            text += ("CoCoaH Frappe  " + 30 + "  Baht\n");
        }
        if(MilkH.isSelected() == true)
        {
            price = price + 20;
            text += ("Milk Hot  " + 20 + "  Baht\n");
        }
        if(MilkI.isSelected() == true)
        {
            price = price + 25;
            text += ("Milk Ice  " + 25 + "  Baht\n");
        }
        if(MilkF.isSelected() == true)
        {
            price = price + 30;
            text += ("Milk Frappe  " + 30 + "  Baht\n");
        }
        if(MilkTeaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Milk Tea Ice  " + 25 + "  Baht\n");
        }
        if(MilkTeaF.isSelected() == true)
        {
            price = price + 30;
            text += ("Milk Tea Frappe  " + 30 + "  Baht\n");
        }
        if(LemonTeaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Lemon Tea Ice  " + 25 + "  Baht\n");
        }
        if(LemonTeaF.isSelected() == true)
        {
            price = price + 30;
            text += ("Lemon Tea Frappe  " + 30 + "  Baht\n");
        }
        if(MiloH.isSelected() == true)
        {
            price = price + 20;
            text += ("Milo Hot  " + 20 + "  Baht\n");
        }
        if(MiloI.isSelected() == true)
        {
            price = price + 25;
            text += ("Milo Ice  " + 25 + "  Baht\n");
        }
        if(MiloF.isSelected() == true)
        {
            price = price + 30;
            text += ("Milo Frappe  " + 30 + "  Baht\n");
        }
        if(NescafeH.isSelected() == true)
        {
            price = price + 20;
            text += ("Nescafe Hot  " + 20 + "  Baht\n");
        }
        if(NescafeI.isSelected() == true)
        {
            price = price + 25;
            text += ("Nescafe Ice  " + 25 + "  Baht\n");
        }
        if(NescafeF.isSelected() == true)
        {
            price = price + 30;
            text += ("Nescafe Frappe  " + 30 + "  Baht\n");
        }
        if(NescafeTeaH.isSelected() == true)
        {
            price = price + 20;
            text += ("Nescafe Tea Hot  " + 20 + "  Baht\n");
        }
        if(NescafeTeaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Nescafe Tea Ice  " + 25 + "  Baht\n");
        }
        if(NescafeTeaF.isSelected() == true)
        {
            price = price + 30;
            text += ("Nescafe Tea Frappe  " + 30 + "  Baht\n");
        }
        if(ItalianSodaF.isSelected() == true)
        {
            price = price + 25;
            text += ("Italian Soda Frappe  " + 25 + "  Baht\n");
        }
        if(RedLimeSodaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Red Lime Soda Ice  " + 25 + "  Baht\n");
        }
        if(HoneyLimeSodaI.isSelected() == true)
        {
            price = price + 25;
            text += ("Honey Lime Soda Ice  " + 25 + "  Baht\n");   
        }
        
        Order.setText(String.valueOf("--------------------Reciept---------------------\r\n" + "***********Coffee Background***********\r\n" + "\n"  + "Date : " + date.toString() +"\n" + text + "Total : " + price + " Baht\n" + "**********************\t\n" + "Save : C:\\Users\\KWANNATTHA\\Documents\\NetBeans\\Reciept.txt"));
        Baht.setText(String.valueOf(price + "  Baht"));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\KWANNATTHA\\Documents\\NetBeans\\Reciept.txt";
        File file = new File(path);
        FileWriter writer;
        try
        {
            writer = new FileWriter(file,true);
            writer.write(Order.getText());
            writer.close();
            
            System.out.println("Write Success");
        }   catch (IOException ex) 
            {
                e.printStackTrace();
            }
        
        JOptionPane.showMessageDialog(null,"Thank you for using the service Coffee Background");
    }//GEN-LAST:event_btnPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswingMilkHandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Americano;
    private javax.swing.JCheckBox AmericanoH;
    private javax.swing.JCheckBox AmericanoI;
    private javax.swing.JLabel Baht;
    private javax.swing.JLabel Cappuccino;
    private javax.swing.JCheckBox CappuccinoF;
    private javax.swing.JCheckBox CappuccinoH;
    private javax.swing.JCheckBox CappuccinoI;
    private javax.swing.JLabel CoCoa;
    private javax.swing.JCheckBox CoCoaF;
    private javax.swing.JCheckBox CoCoaH;
    private javax.swing.JCheckBox CoCoaI;
    private javax.swing.JLabel Esspresso;
    private javax.swing.JCheckBox EsspressoF;
    private javax.swing.JCheckBox EsspressoH;
    private javax.swing.JCheckBox EsspressoI;
    private javax.swing.JLabel Frappe1;
    private javax.swing.JLabel Frappe2;
    private javax.swing.JLabel GreenTea;
    private javax.swing.JCheckBox GreenTeaF;
    private javax.swing.JCheckBox GreenTeaH;
    private javax.swing.JCheckBox GreenTeaI;
    private javax.swing.JCheckBox HoneyLimeSodaI;
    private javax.swing.JLabel HoneylimeSoda;
    private javax.swing.JLabel Hot1;
    private javax.swing.JLabel Hot2;
    private javax.swing.JLabel Ice1;
    private javax.swing.JLabel Ice2;
    private javax.swing.JLabel ItalianSoda;
    private javax.swing.JCheckBox ItalianSodaF;
    private javax.swing.JLabel Latte;
    private javax.swing.JCheckBox LatteF;
    private javax.swing.JCheckBox LatteH;
    private javax.swing.JCheckBox LatteI;
    private javax.swing.JLabel LemonTea;
    private javax.swing.JCheckBox LemonTeaF;
    private javax.swing.JCheckBox LemonTeaI;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Milk;
    private javax.swing.JCheckBox MilkF;
    private javax.swing.JCheckBox MilkH;
    private javax.swing.JCheckBox MilkI;
    private javax.swing.JLabel MilkTea;
    private javax.swing.JCheckBox MilkTeaF;
    private javax.swing.JCheckBox MilkTeaI;
    private javax.swing.JLabel Milo;
    private javax.swing.JCheckBox MiloF;
    private javax.swing.JCheckBox MiloH;
    private javax.swing.JCheckBox MiloI;
    private javax.swing.JLabel Nescafe;
    private javax.swing.JCheckBox NescafeF;
    private javax.swing.JCheckBox NescafeH;
    private javax.swing.JCheckBox NescafeI;
    private javax.swing.JLabel NescafeTea;
    private javax.swing.JCheckBox NescafeTeaF;
    private javax.swing.JCheckBox NescafeTeaH;
    private javax.swing.JCheckBox NescafeTeaI;
    private javax.swing.JTextPane Order;
    private javax.swing.JLabel Price;
    private javax.swing.JCheckBox RedLimeSodaI;
    private javax.swing.JLabel RedlimeSoda;
    private javax.swing.JLabel ThaiTea;
    private javax.swing.JCheckBox ThaiTeaF;
    private javax.swing.JCheckBox ThaiTeaH;
    private javax.swing.JCheckBox ThaiTeaI;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPayment;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
